ALTER TABLE public.locations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.locations ADD CONSTRAINT locations_location_name_unique UNIQUE (location_name);
ALTER TABLE public.locations ADD CONSTRAINT locations_project_id_unique UNIQUE (project_id);
