ALTER TABLE public.projects DROP COLUMN IF EXISTS site;
ALTER TABLE public.projects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.projects RENAME COLUMN created_by TO created_at;
ALTER TABLE public.projects ADD created_by text;
ALTER TABLE public.projects ADD site_id int4;
